# Содержание
1. [Операции над матрицами](#операции-над-матрицами)
   
   A. [Сложение и вычитание матриц](#сложение-и-вычитание-матриц)
      - [Сложение матриц](#сложение-матриц)
      - [Вычитание матриц](#вычитание-матриц)

   B. [Умножение матрицы на константу](#умножение-матрицы-на-константу)
   
   C. [Умножение матрицы на матрицу](#умножение-матрицы-на-матрицу)
   
   D. [Транспонирование матрицы](#транспонирование-матрицы)
   
   E. [Использование единичной и обратной матриц](#использование-единичной-и-обратной-матриц)
   
   F. [Ранг матрицы](#ранг-матрицы)
   
   G. [Определитель матрицы](#определитель-матрицы)

# Операции над матрицами

Python предоставляет несколько библиотек для работы с матрицами, такие как NumPy, SciPy, SymPy и другие. Для начала импортируем необходимы библиотеки:

In [1]:
import numpy as np
import sympy as sp

## Сложение и вычитание матриц

Матрицы могут быть сложены или вычитаны путём поэлементного сложения соответствующих элементов двух матриц одинакового размера. Эта операция доступна во всех библиотеках, которые поддерживают работу с матрицами.

### Сложение матриц

**Numpy**

In [2]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Сложение двух матриц
C = A + B
D = np.add(A, B)

# Вывод результата
print("Результат сложения двух матриц:")
print(C)
print(D)

Результат сложения двух матриц:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


**Sympy**

In [3]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Сложение двух матриц
C = A + B

# Вывод результата
print("Результат сложения двух матриц:")
C

Результат сложения двух матриц:


Matrix([
[ 6,  8],
[10, 12]])

## Вычитание матриц

**Numpy**

In [4]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Вычитание матриц
C = A - B

# Вывод результата
print(C)

[[-4 -4]
 [-4 -4]]


**Sympy**

In [5]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Вычитание матриц
C = A - B

# Вывод результата
C

Matrix([
[-4, -4],
[-4, -4]])

## Умножение матрицы на константу

**Numpy**

In [6]:
# Создание матрицы
A = np.array([[1, 2], [3, 4]])

# Умножение матрицы на константу
k = 2
B = k * A
C = np.multiply(k, A)

# Вывод результата
print(B)
print(C)

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


**Sympy**

In [7]:
# Создание матрицы
A = sp.Matrix([[1, 2], [3, 4]])

# Умножение матрицы на константу
k = 2
B = A.multiply(k)

# Вывод результата
B

Matrix([
[2, 4],
[6, 8]])

## Умножение матрицы на матрицу

**Numpy**

In [8]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Умножение матриц
C = A @ B
D = np.dot(A, B)

# Вывод результата
print(C)
print(D)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**Sympy**

In [9]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Умножение матриц
C = A * B

# Вывод результата
C

Matrix([
[19, 22],
[43, 50]])

## Транспонирование матрицы

**Numpy**

In [10]:
# Создание матрицы
A = np.array([[1, 2], [3, 4], [5, 6]])

# Транспонирование матрицы
B = np.transpose(A)
C = A.T

# Вывод результата
print("Исходная матрица")
print(A)
print("Транспонированная матрица")
print(B)
print(C)

Исходная матрица
[[1 2]
 [3 4]
 [5 6]]
Транспонированная матрица
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


**Sympy**

In [11]:
# Создание матрицы
A = sp.Matrix([[1, 2], [3, 4], [5, 6]])

# Транспонирование матрицы
B = A.transpose()
C = A.T

# Вывод результата
print("Исходная матрица")
display(A)
print("Транспонированная матрица")
display(B,
        C,)

Исходная матрица


Matrix([
[1, 2],
[3, 4],
[5, 6]])

Транспонированная матрица


Matrix([
[1, 3, 5],
[2, 4, 6]])

Matrix([
[1, 3, 5],
[2, 4, 6]])

## Использование единичной и обратной матриц

**Numpy**

In [12]:
# Создание единичной матрицы 3x3
I = np.eye(3)

# Вывод результата
print("Единичная матрица")
I

Единичная матрица


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Создание матрицы 2x2
A = np.array([[1, 2], [3, 4]])

# Обращение матрицы
A_inv = np.linalg.inv(A)

# Вывод результата
print("Обратная матрица")
A_inv

Обратная матрица


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Sympy**

In [14]:
# Создание единичной матрицы 3x3
I = sp.eye(3)

# Вывод результата
print("Единичная матрица")
I

Единичная матрица


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [15]:
# Создание матрицы 2x2
A = sp.Matrix([[1, 2], [3, 4]])

# Обращение матриц
A_inv = A.inv()

# Вывод результата
A_inv

Matrix([
[ -2,    1],
[3/2, -1/2]])

## Ранг матрицы

**Numpy**

In [16]:
# Создание единичной матрицы 3x3
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисление ранга матрицы
rank = np.linalg.matrix_rank(matrix)

# Вывод результата
print("Матрица\n", matrix)
print("Ранг матрицы", rank)

Матрица
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы 2


**Sympy**

In [17]:
# Создание единичной матрицы 3x3
matrix = sp.Matrix([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисление ранга матрицы
rank = matrix.rank()

# Вывод результата
print("Матрица:")
display(matrix)
print("Ранг матрицы", rank)

Матрица:


Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

Ранг матрицы 2


## Определитель матрицы

**Numpy**

In [18]:
# Создание единичной матрицы 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Вычисление определителя матрицы
det_A = np.linalg.det(A)

# Вывод результата
print("Матрица\n", A)
print("Определитель матрицы", det_A)

Матрица
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель матрицы 0.0


**Sympy**

In [19]:
# Создание единичной матрицы 3x3
A = sp.Matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Вычисление определителя матрицы
det_A = A.det()

# Вывод результата
print("Матрица:")
display(A)
print("Определитель матрицы", det_A)

Матрица:


Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

Определитель матрицы 0
