# Содержание
1. [Сравнение numpy и sympy](#сравнение-numpy-и-sympy)

2. [Операции с векторами](#операции-с-векторами)
   
   A. [Вычисление длины вектора](#вычисление-длины-вектора)

   B. [Сложение векторов](#сложение-векторов)
   
   C. [Вычитание векторов](#вычитание-векторов)
   
   D. [Умножение вектора на константу](#умножение-вектора-на-константу)
   
   E. [Скалярное произведение векторов](#скалярное-произведение-векторов)
   
   F. [Векторное произведение векторов](#векторное-произведение-векторов)
   
   G. [Вычисление расстояния между векторами](#вычисление-расстояния-между-векторами)


# Сравнение numpy и sympy

NumРy и SуmРy - две библиотеки для работы с числовыми данными в Python. Некоторые отличия между ними:
- NumРy-это библиотека для работы с массивами чисел и матрицами, а SуmРу - это библиотека для работы с символьными выражениями.
- NumРy предоставляет множество быстрых и эффективных функций для работы с массивами чисел, таких как математические операции, операции срезов, агрегирующие функции и др. SуmРу же предоставляет функции для символьных вычислений, таких как упрощение выражений, дифференцирование и интегрирование, решение уравнений и систем уравнении
- NumРу используются числа с плавающеи запятои (float), a в SymPy - символьные переменные (Symbol).
- NumPy предназначен для работы с числами, и матрицами, используя численные методы, тогда каk SуmРу предоставляет возможность работы с математическими выражениями и символьными переменными.
- NumРу-это библиотека для вычислений на массивах, а SуmРy- это символьный математический пакет.

NumPy u SymPy - это две разные библотеки с разными задачами и функциональностъю. Если вам нужно работать с числами и матрицами, используя численные методы, то лучше использовать NumPy. Если вам нужно работать с символьными выпажениями, то лучше использовать SymРy.

# Операции с векторами

Для начала импортируем необходимые библиотеки:

In [1]:
import numpy as np
import sympy as sp
import scipy as sc

## Вычисление длины вектора

**Numpy**

В NumPy для вычисления длины вектора можно использовать функцию numpy `numpy.linalg.norm()`. Функция принимает вектор как аргумент и возвращает его длину (норму). Параметр `ord` отвечает за тип нормы вектора, по умолчанию он равен 2 (L2 или евклидова норма)

Вот пример кода, который вычисляет длину вектора (2, 3, 4) с помощью функции numpy.linalg.norm():

In [2]:
v = np.array([2, 3, 4])
lenght = np.linalg.norm(v)  # по умолчанию вычисляется L2 или евклидова норма
print(lenght)

lenght = np.linalg.norm(v, ord=1)  # вычисляется L1 или манхэттенская норма
print(lenght)

lenght = np.linalg.norm(v, ord=3)  # вычисляется L3 или кубическая норма
print(lenght)

5.385164807134504
9.0
4.626065009182741


## Сложение векторов

**Numpy**

В библиотеке NumPy сложение векторов можно выполнить с помощью оператора +. Для выполнения сложения векторов необходимо, чтобы векторы имели одинаковую длину. В противном случае, возникнет ошибка.

Вот пример кода, который выполняет сложение двух векторов (1, 2, 3) и (4, 5, 6) в NumPy:

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v_sum = v1 + v2

print(v_sum)

[5 7 9]


**Sympy**

В библиотеке SymPy сложение векторов можно выполнить с помощью функции sympy.Matrix. Для выполнения сложения векторов необходимо создать матрицы-столбцы из векторов с помощью функции sympy.Matrix и затем применить операцию сложения +.

Вот пример кода, который выполняет сложение двух векторов (1, 2, 3) и (4, 5, 6) в SymPy:

In [4]:
v1 = sp.Matrix([1, 2, 3])
v2 = sp.Matrix([4, 5, 6])
v_sum = v1 + v2

print(v_sum)

Matrix([[5], [7], [9]])


## Вычитание векторов

**Numpy**

В библиотеке NumPy вычитание векторов можно выполнить с помощью оператора -. Для выполнения вычитания векторов необходимо, чтобы векторы имели одинаковую длину. В противном случае, возникнет ошибка.

Вот пример кода, который выполняет вычитание векторов (1, 2, 3) и (4, 5, 6) в NumPy:

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v_diff = v1 - v2

print(v_diff)

[-3 -3 -3]


**Sympy**

В SymPy можно вычислить разность между двумя векторами, используя функцию Matrix, которая позволяет создавать матрицы любого размера, в том числе векторы.

In [6]:
# создаем векторы
v1 = sp.Matrix([1, 2, 3])
v2 = sp.Matrix([4, 5, 6])

# вычисляем разность векторов
v_diff = v1 - v2

print(v_diff)

Matrix([[-3], [-3], [-3]])


## Умножение вектора на константу

**Numpy**

В NumPy можно умножать векторы на константы, используя оператор умножения *. Для этого нужно передать вектор и константу как аргументы этого оператора. Пример:

In [7]:
a = np.array([1, 2, 3])  # вектор
k = 2                   # константа

b = k * a               # умножение вектора на константу

print(b)

[2 4 6]


**Sympy**

Для умножения вектора на константу в Sympy можно воспользоваться функцией sympy.Matrix, которая позволяет создавать матрицы и векторы в символьном виде.

Пример умножения вектора на константу:

In [8]:
a = sp.Matrix([1, 2, 3])  # вектор
k = 2                   # константа

b = k * a               # умножение вектора на константу

print(b)

Matrix([[2], [4], [6]])


## Скалярное произведение векторов

**Numpy**

В NumPy скалярное произведение векторов может быть вычислено с помощью функции np.dot() или метода .dot().

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# вычисление скалярного произведения с помощью функции np.dot()
dot_product = np.dot(a, b)
print(dot_product)  # 32

# вычисление скалярного произведения с помощью метода .dot()
dot_product = a.dot(b)
print(dot_product)  # 32

32
32


**Sympy**

В библиотеке Sympy можно использовать класс sympy.Matrix для работы с матрицами и векторами. Чтобы вычислить скалярное произведение векторов с помощью этого класса, необходимо использовать метод dot().

In [10]:
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])

dot_product = a.dot(b)
print(dot_product)  # 32

32


## Векторное произведение векторов

**Numpy**

В библиотеке NumPy векторное умножение (произведение) двух векторов можно выполнить с помощью функции cross().

In [11]:
# определение двух векторов
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# вычисление векторного произведения
v_cross = np.cross(v1, v2)
print("Векторное произведение:", v_cross)

Векторное произведение: [-3  6 -3]


**Sympy**

В библиотеке Sympy векторное умножение двух векторов можно выполнить с помощью функции cross(). Векторы должны быть заданы с помощью класса sympy.vector.CoordSys3D и sympy.vector.cross.

Вот пример использования функции cross() для векторного умножения двух векторов в SymPy:

In [12]:
from sympy.vector import CoordSys3D, cross
N = CoordSys3D("N")  # Создание трехмерной декартовой системы координат

# Определение двух векторов
v1 = 1 * N.i + 2 * N.j + 3 * N.k
v2 = 4 * N.i + 5 * N.j + 6 * N.k

# Вычисление векторного произведения
v_cross = cross(v1, v2)

# Вывод результата
print("Векторное произведение:", v_cross)

Векторное произведение: (-3)*N.i + 6*N.j + (-3)*N.k


## Вычисление расстояния между векторами

**Numpy**

В библиотеке NumPy расстояние между двумя векторами можно вычислить с помощью функции numpy.linalg.norm().

Вот пример использования функции numpy.linalg.norm() для вычисления расстояния между двумя векторами в NumPy:

In [13]:
# определение двух векторов
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# вычисление расстояния между векторами по норме L2
distance = np.linalg.norm(v2 - v1)

# вывод результата
print("Расстояние между векторами по норме L2:", distance)

# вычисление расстояния между векторами по норме L1
distance = np.linalg.norm(v2 - v1, ord=1)

# вывод результата
print("Расстояние между векторами по норме L1:", distance)

Расстояние между векторами по норме L2: 5.196152422706632
Расстояние между векторами по норме L1: 9.0


В библиотеке NumPy нет прямой реализации вычисления косинусного расстояния между векторами. Можно реализовать такую функцию самостоятельно или воспользоваться библиотекой SciPy.

In [14]:
# создаем два вектора
x = np.array([1, 2, 3])
y = np.array([4, 5, 5])

# вычисляем косинусное расстояние по формуле
cosine_distance = 1- np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

print(cosine_distance)

from scipy.spatial import distance
cosine_distance = distance.cosine(x, y)

print(cosine_distance)

0.04597004230833501
0.04597004230833501


**Sympy**

Векторы в sympy можно задать с помощью функции Matrix. Расстояние между двумя векторами можно найти с помощью метода norm().

In [15]:
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])

# расстояние L2 между ними можно найти так:
distance = (a - b).norm()

# В результате переменная 'distance' будет содержать значение 'sqrt(27)'.python-version
# Если нужно получить численное значение, можно использовать метод 'evalf()':
print(distance)
print(distance.evalf())

# расстояние L1 можно найти так:
distance = (a - b).norm(ord=1)
print(distance.evalf())

3*sqrt(3)
5.19615242270663
9.00000000000000


Косинусное расстояние напрямую не реализовано в библиотеке SymPy